using .Method_ranking
using Test

@testset "Method_ranking.jl" begin
    @test rank_methods(["RYYVLZVUVIJVGH-UHFFFAOYSA-N", "IISBACLAFKSPIT-UHFFFAOYSA-N", "COLNVLDHVKWLRT-QMMMGPOBSA-N", "ZYGHJZDHTFUPRJ-UHFFFAOYSA-N", "CMPQUABWPXYYSH-UHFFFAOYSA-N", "MUMGGOZAMZWBJJ-DYKIIFRCSA-N", "CBCKQZAAMUWICA-UHFFFAOYSA-N", "OYGQVDSRYXATEL-UHFFFAOYSA-N", "BSYNRYMUTXBXSQ-UHFFFAOYSA-N", "UFWIBTONFRDIAS-UHFFFAOYSA-N"])[1,"Score"] == 38.9696
    @test rank_methods(["CN1C=NC2=C1C(=O)N(C(=O)N2C)C", "CC(C)(C1=CC=C(C=C1)O)C2=CC=C(C=C2)O", "C1=CC=C(C=C1)C[C@@H](C(=O)O)N "])[2,"Score"] == 56.2719
    @test rank_methods(["CN1C=NC2=C1C(=O)N(C(=O)N2C)C", "CC(C)(C1=CC=C(C=C1)O)C2=CC=C(C=C2)O"])[2,"Score"] == 56.2719
end
